### ISSUE TITLE
e2e Test failures

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#1101]
The e2e tests appear to be failing due to changes from #1097.  Looking into it.  Not sure why the CI didn't catch this with #1097's commit....

```
HEAD is now at 2c632d1a Merge pull request #1824 from cyphar/fix-mips-build-devNumber
ln -sf ../../opencontainers/runc/runc
# github.com/containers/buildah/tests/e2e
tests/e2e/buildah_suite_test.go:233:2: too many arguments to return
	have ([]byte, error)
	want (error)
tests/e2e/buildah_suite_test.go:279:18: multiple-value copy.Image() in single-value context
Error: source package github.com/containers/buildah/tests/e2e does not pass go vet.
make: *** [validate] Error 1
```

**Comment by TomSweeneyRedHat** [comment]
Fixed with a number of PR's.  Main issue was a change in behaviour between go v1.10 and v1.11 in it's gofmt code checking code.  Code that passed gofmt in 1.10 failed in 1.11 and vice verse.
